#!/usr/bin/env python
import sys

if len(sys.argv) < 2:
	print('Usage: %s <input file>' % sys.argv[0], file=sys.stderr)
	sys.exit()

infile = open(sys.argv[1], 'rb')
linenum = 0
while True:
	line = infile.readline()
	if line == b'':
		break
	linenum += 1

	if not all(char < 128 for char in line):
		try:
			print('line %i utf8: %s' % (linenum, line.decode('utf-8').strip('\r\n')))
		except UnicodeDecodeError:
			print('line %i latin1: %s' % (linenum, line.decode('latin1').strip('\r\n')))
infile.close()
