#!/usr/bin/env python
import os
import sys

def printError(str):
	print('\033[91m' + str + '\033[0m', file=sys.stderr)

def processFile(file, infile):
	linenum = 0
	for line in infile:
		linenum += 1
		if any(char >= 128 for char in line):
			linestart = file + ': line ' + str(linenum)
			try:
				print(linestart + ' utf8: ' + line.decode('utf8').strip('\r\n'))
			except UnicodeDecodeError:
				print(linestart + ' latin1: ' + line.decode('latin1').strip('\r\n'))

files = sys.argv[1:]
if len(files) == 0:
	print('Usage: ' + os.path.basename(sys.argv[0]) + ' <input files>', file=sys.stderr)
	sys.exit(1)

ret = 0
for file in files:
	try:
		with open(file, 'rb') as infile:
			processFile(file, infile)
	except OSError as e:
		printError(file + ': ' + e.strerror)
		ret = 1
sys.exit(ret)
