#!/usr/bin/env python
import os
import sys
import tempfile

def printError(str):
	print('\033[91m' + str + '\033[0m', file=sys.stderr)

namesOld = sys.argv[1:]
if len(namesOld) == 0:
	print('Usage: ' + sys.argv[0] + ' <files to be renamed>', file=sys.stderr)
	sys.exit(1)

with tempfile.NamedTemporaryFile('w', delete=False) as file:
	filename = file.name

try:
	with open(filename, 'w', errors='replace') as file: # NamedTemporaryFile does not have errors parameter
		for arg in namesOld:
			file.write(arg + '\n')

	ret = os.system('vim ' + filename)
	if ret != 0:
		raise EnvironmentError('Editor returned error code: ' + str(ret))

	with open(filename, 'r') as file:
		namesNew = file.readlines()
finally:
	os.remove(filename)

if len(namesOld) != len(namesNew):
	printError('Different number of lines: original ' + str(len(namesOld)) + ', new ' + str(len(namesNew)))
	sys.exit(1)

ret = 0
for index in range(0, len(namesOld)):
	nameOld = namesOld[index].strip()
	nameNew = namesNew[index].strip()
	if nameOld == nameNew:
		continue

	if not os.path.exists(nameOld):
		printError('File ' + nameOld + ' does not exist.')
		ret = 1
	elif os.path.exists(nameNew):
		printError('File ' + nameNew + ' already exists.')
		ret = 1
	else:
		try:
			os.rename(nameOld, nameNew)
		except EnvironmentError as e:
			printError('Cannot rename ' + nameOld + ': ' + e.strerror)
			ret = 1
sys.exit(ret)
