#!/usr/bin/env python
import os
import re
import shutil
import sys
import tempfile

def fatal(str):
	print('\033[91m' + str + '\033[0m', file=sys.stderr)
	sys.exit(1)

def toFullMillis(hours, minutes, secs, millis):
	return int(millis) + 1000 * (int(secs) + 60 * (int(minutes) + (60 * int(hours))))

def toSrt(fullMillis):
	millis = fullMillis
	secs = millis // 1000
	minutes = secs // 60
	hours = minutes // 60
	millis %= 1000
	secs %= 60
	minutes %= 60
	return b'%02i:%02i:%02i,%03i' % (hours, minutes, secs, millis)

if len(sys.argv) < 2:
	print('Usage: %s [from, to] <command> <SRT file to edit>\n\n'
		'command:\n'
		'    verify    check SRT file for common format problems\n'
		'    fix    rewrite SRT file to fix some format problems\n'
		'    +<millis>    forward subtitles for amount of milliseconds\n'
		'    -<millis>    backward subtitles for amount of milliseconds\n\n'
		'from, to:\n'
		'    from:<seconds>    time index from which do retime (optional)\n'
		'    to:<seconds>    time index to which do retime (optional)'
	% sys.argv[0], file=sys.stderr)
	sys.exit()

if len(sys.argv) < 3:
	fatal('Missing arguments')

i = 1

millisFrom = -1
millisTo = -1
while i < len(sys.argv) - 2:
	m = re.match('^(from|to):([0-9]+)$', sys.argv[i])
	if not m:
		break
	if m.group(1) == 'from':
		millisFrom = int(m.group(2)) * 1000
	else:
		millisTo = int(m.group(2)) * 1000
	i += 1

process = 0
diff = 0
if sys.argv[i] == 'fix':
	process = 1
elif re.match('^[-+][0-9]+$', sys.argv[i]):
	process = 1
	diff = int(sys.argv[i])
elif sys.argv[i] != 'verify':
	fatal('Invalid argument: %i' % i)

i += 1

infile = open(sys.argv[i], 'rb')
outfile = False
outname = ''
extraText = ''
if process:
	outfile = tempfile.NamedTemporaryFile('wb', delete=False)
	outname = outfile.name
	extraText = '[FIXING] '
try:
	state = 0
	linenum = 0
	subnum = 0
	subnumWrite = 0
	lastMillis = 0
	while True:
		line = infile.readline()
		if line == b'':
			break
		linenum += 1

		mc = re.match(b'^([^\r\n]*)([\r\n]*)$', line)
		content = mc.group(1)

		if mc.group(2) != b'\r\n':
			print('%sline %i: Invalid newline' % (extraText, linenum))

		if state == 0:
			if content == b'':
				print('%sline %i: Extra blank line' % (extraText, linenum))
				continue

			m = re.match(b'^[0-9]+$', content)
			if not m:
				fatal('line %i: Invalid format' % linenum)

			if int(content) != subnum + 1:
				print('%sline %i: Invalid subtitle number' % (extraText, linenum))
			subnum = int(content)

			if process:
				subnumWrite += 1
				outfile.write(b'%i\r\n' % subnumWrite)

			state = 1
		elif state == 1:
			m = re.match(b'^([0-9]{2}):([0-9]{2}):([0-9]{2}),([0-9]{3,4}) --> ([0-9]{2}):([0-9]{2}):([0-9]{2}),([0-9]{3,4})$', content)
			if not m:
				fatal('line %i: Invalid format' % linenum)
			if len(m.group(4)) == 4 or len(m.group(8)) == 4:
				print('%sline %i: Wrong millis format' % (extraText, linenum))

			millis1 = toFullMillis(m.group(1), m.group(2), m.group(3), m.group(4))
			millis2 = toFullMillis(m.group(5), m.group(6), m.group(7), m.group(8))

			if millis1 >= millis2:
				print('line %i: Invalid time interval' % linenum)
			if millis1 < lastMillis:
				print('line %i: Overlap' % linenum)
			lastMillis = millis2

			if process:
				if (millisFrom == -1 or millisFrom <= millis1) and (millisTo == -1 or millisTo > millis1):
					millis1 += diff
					millis2 += diff
				outfile.write(b'%s --> %s\r\n' % (toSrt(millis1), toSrt(millis2)))

			state = 2
		elif state == 2:
			if process:
				outfile.write(b'%s\r\n' % content)
			if content == b'':
				state = 0

	if state != 0:
		print('%sline %i: Invalid end of file' % (extraText, linenum))
	if process and state == 2:
		outfile.write(b'\r\n')

	infile.close()

	if process:
		outfile.close()
		shutil.copy(outname, sys.argv[i])
finally:
	if process:
		os.remove(outname)
